# Generated by Django 6.1.1 on 2026-09-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_choice_question_delete_person_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
