# Generated by Django 6.1.1 on 2026-09-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=34)),
                ('category', models.CharField(blank=True, choices=[('Summer', 'Summer'), ('Collection', 'Collection')], max_length=34)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
