# Generated by Django 6.1.1 on 2026-09-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, choices=[('Summer', 'Summer'), ('Collection', 'Collection')], max_length=34),
        ),
    ]
