# Generated by Django 6.1.1 on 2026-09-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, choices=[('Winter Collection', 'Winter Collection'), ('Summer Collection', 'Summer Collection')]),
        ),
    ]
