# Generated by Django 6.1.1 on 2026-09-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='990', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.TextField(default='read this before shipping'),
        ),
        migrations.AddField(
            model_name='product',
            name='washcare',
            field=models.TextField(choices=[('this is cotton 501 washcare tips', 'COTTON 501'), ('this is Nylon washcare tips', 'NYLON')], default='hii'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('Winter Collection', 'Winter Collection'), ('Summer Collection', 'Summer Collection')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
